### ISSUE TITLE
Trouble setting up the project

### ISSUE THREAD

**Issue by AlySemsem** [raphaelsulzer/dgnn#7]
hello,
I have been following the instructions step-by-step for setting up the project but when I reached the 3rd step of the installation 
--"python utils/setup_libmesh_convonet.py build_ext --inplace" 
it gives me this error : "ValueError: 'libmesh\triangle_hash.pyx' doesn't match any files"
even though the file is there just fine. Is there something that I should have installed before this?
Thank you.

**Comment by raphaelsulzer** [comment]
Hi and sorry for the late reply.
You need to enter the utils folder first. Try this:
```
cd utils
python setup_libmesh_convonet.py build_ext --inplace
```
